overview:
  entity: singing-kangaroo
  project: Curriculum Learning Convection Equation
  group: Hyperparameter Search for Optimizer; Curriculum Learning
  experiment: lbfgs-hyperparameter-curriculum-learning-sweep
  description: >
    LBFGS Optimizer Hyperparameter Sweep for Curriculum Learning
    with fixed curriculum learning parameters, sampling space, and model
    and loss.
  version: v0.0.1
  run_mode: online

sweep:
  name: lbfgs-hyperparameter-curriculum-learning-sweep
  description: L-BFGS Optimizer Hyperparameter Sweep for Curriculum Learning
  method: bayes
  metric:
    name: Loss Overall
    goal: minimize
  parameters:
    optimizer:
      parameters:
        name:
          value: LBFGS
        lr:
          values: [2, 1, 0.5, 0.1]
        max_iter:
          values: [5, 10, 20]
        history_size:
          values: [25, 50, 100]
        line_search_fn:
          values: ["strong_wolfe", None]
    training:
      parameters:
        epochs:
          values: [50, 100, 250, 500]

learning:
  device: cuda
  curriculum: True
  # seed: 0

model:
  name: ConvectionPINNModel
  input_dim: 2
  hidden_dim: 50

loss:
  name: ConvectionMSEPDELoss
  convection: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]
  regularization: 1

scheduler:
  end: 29
  start: 0
  step: 1

  data:
    train:
      batch_size: full
      shuffle: False
      sampler:
        name: RandomSampler
        replacement: True
        num_samples: 100
      pde:
        convection: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]
        l: 6.283185307179586
        n: 100
        snr: 0
        t: 1

    validation:
      batch_size: full
      shuffle: False
      pde:
        convection: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]
        l: 6.283185307179586
        n: 1
        snr: 0
        t: 1

    test:
      batch_size: full
      shuffle: False
      pde:
        convection: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]
        l: 6.283185307179586
        n: 100
        snr: 0
        t: 1
