overview:
  entity: singing-kangaroo
  project: Curriculum Learning Convection Equation
  group: SGD Hyperparameter Search
  experiment: sgd-hyperparameter-curriculum-learning-sweep
  description: >
    SGD Optimizer Hyperparameter Sweep for Curriculum Learning
    with fixed curriculum learning parameters, sampling space, and model
    and loss.
  version: v0.0.1
  run_mode: online

sweep:
  name: sgd-hyperparameter-curriculum-learning-sweep
  description: SGD Optimizer Hyperparameter Sweep for Curriculum Learning
  method: bayes
  metric:
    name: Loss Overall
    goal: minimize
  parameters:
    optimizer:
      parameters:
        name:
          value: SGD
        lr:
          min: 0.0001
          max: 0.1
        momentum:
          min: 0.1
          max: 0.9
        weight_decay:
          min: 0.0
          max: 0.1
        nesterov:
          values: [True, False]
    training:
      parameters:
        epochs:
          value: 250

learning:
  device: cuda
  curriculum: True
  count: 150
  # seed: 0

model:
  name: ConvectionPINNModel
  input_dim: 2
  hidden_dim: 50

loss:
  name: ConvectionMSEPDELoss
  convection: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]
  regularization: 1

scheduler:
  end: 29
  start: 0
  step: 1

  data:
    train:
      batch_size: full
      shuffle: False
      sampler:
        name: RandomSampler
        replacement: False
        num_samples: 100
      pde:
        convection: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]
        l: 6.283185307179586
        n: 100
        snr: 50
        t: 1

    validation:
      batch_size: full
      shuffle: False
      pde:
        convection: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]
        l: 6.283185307179586
        n: 1
        snr: 0
        t: 1

    test:
      batch_size: full
      shuffle: False
      pde:
        convection: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]
        l: 6.283185307179586
        n: 100
        snr: 0
        t: 1
