overview:
  entity: singing-kangaroo
  project: Curriculum Learning Convection Equation
  group: L-BFGS Hyperparameter Search Baseline
  experiment: lbfgs-hyperparameter-baseline-sweep
  description: >
    LBFGS Optimizer Hyperparameter Sweep for Baseline Training
    with fixed curriculum learning parameters, sampling space, and model
    and loss.
  version: v0.0.1
  run_mode: online

sweep:
  name: lbfgs-hyperparameter-baseline-sweep
  description: L-BFGS Optimizer Hyperparameter Sweep for Baseline Training
  method: bayes
  metric:
    name: Loss Overall
    goal: minimize
  parameters:
    optimizer:
      parameters:
        name:
          value: LBFGS
        lr:
          min: 0.01
          max: 2
        max_iter:
          values: [5, 10, 20]
        history_size:
          values: [25, 50, 100]
        line_search_fn:
          value: strong_wolfe
    training:
      parameters:
        epochs:
          value: 250

learning:
  device: cuda
  curriculum: False
  count: 150
  # seed: 0

model:
  name: ConvectionPINNModel
  input_dim: 2
  hidden_dim: 50

loss:
  name: ConvectionMSEPDELoss
  convection: [30]
  regularization: 1

scheduler:
  end: 0
  start: 0
  step: 1

  data:
    train:
      batch_size: full
      shuffle: False
      sampler:
        name: RandomSampler
        replacement: False
        num_samples: 100
      pde:
        convection: [30]
        l: 6.283185307179586
        n: 100
        snr: 50
        t: 1

    validation:
      batch_size: full
      shuffle: False
      pde:
        convection: [30]
        l: 6.283185307179586
        n: 1
        snr: 0
        t: 1

    test:
      batch_size: full
      shuffle: False
      pde:
        convection: [30]
        l: 6.283185307179586
        n: 100
        snr: 0
        t: 1
