overview:
  name: "Test of Convection Equation Curriculum Learning"
  description: "Test of Curriculum Learning for Convection Equation"
  version: "0.0.1"
model:
  input_dim: 2
  hidden_dim: 50
optimizer:
  name: Adam
  lr: 0.01
  weight_decay: 0.01
loss:
  name: ConvectionLoss
  custom: True
scheduler:
  data:
    batch_size: 64
    shuffle: False
  pde:
    convection:
      [
        1,
        2,
        3,
        4,
        5,
        6,
        7,
        8,
        9,
        10,
        11,
        12,
        13,
        14,
        15,
        16,
        17,
        18,
        19,
        20,
        21,
        22,
        23,
        24,
        25,
        26,
        27,
        28,
        29,
        30,
      ]
    l: 6.283185307179586
    n: 50
    snr: 0
    t: 1
  curriculum:
    baseline: false
    end: 29
    start: 0
    step: 1
training:
  epochs: 50
