overview:
  entity: "singing-kangaroo"
  project: "Curriculum Learning Convection Equation"
  group: "SGD Optimizer; Curriculum Learning"
  name: "Convection Equation Curriculum Learning"
  description: "Curriculum Learning for Convection Equation"
  version: "0.0.1"
learning:
  curriculum: True
model:
  input_dim: 2
  hidden_dim: 50
optimizer:
  name: SGD
  lr: 0.0005
  weight_decay: 0.001
  momentum: 0.9
  nesterov: True
loss:
  name: ConvectionLoss
  custom: True
  regularization: 1
scheduler:
  data:
    batch_size: full
    shuffle: False
  pde:
    convection:
      [
        1,
        2,
        3,
        4,
        5,
        6,
        7,
        8,
        9,
        10,
        11,
        12,
        13,
        14,
        15,
        16,
        17,
        18,
        19,
        20,
        21,
        22,
        23,
        24,
        25,
        26,
        27,
        28,
        29,
        30,
      ]
    l: 6.283185307179586
    n: 100
    snr: 0
    t: 1
  curriculum:
    end: 29
    start: 0
    step: 1
training:
  epochs: 500
  stopping:
    patience: 25
