overview:
  project: "Curriculum Learning Convection Equation"
  # id: "Convection Curriculum Learning Test 1"
  group: "Adam Optimizer; Curriculum Learning"
  name: "Convection Equation Curriculum Learning"
  description: "Curriculum Learning for Convection Equation"
  version: "0.0.1"
learning:
  curriculum: True
model:
  input_dim: 2
  hidden_dim: 50
optimizer:
  name: Adam
  lr: 0.01
  weight_decay: 0.01
loss:
  name: ConvectionLoss
  custom: True
scheduler:
  data:
    batch_size: full
    shuffle: False
  pde:
    convection:
      [
        1,
        2,
        3,
        4,
        5,
        6,
        7,
        8,
        9,
        10,
        11,
        12,
        13,
        14,
        15,
        16,
        17,
        18,
        19,
        20,
        21,
        22,
        23,
        24,
        25,
        26,
        27,
        28,
        29,
        30,
      ]
    l: 6.283185307179586
    n: 100
    snr: 0
    t: 1
  curriculum:
    end: 29
    start: 0
    step: 1
training:
  epochs: 100
  stopping:
    patience: 10
