overview:
  entity: serge-kotchourko
  project: Curriculum Learning Convection Equation
  group: Test; Adam Optimizer; Curriculum Learning
  job_type: Training
  experiment: test-adam-curriculum-learning
  description: Curriculum Learning for Convection Equation
  version: v0.0.1
  run_mode: disabled

learning:
  device: cuda
  curriculum: True
  # seed: 0

model:
  name: ConvectionPINNModel
  input_dim: 2
  hidden_dim: 50

optimizer:
  name: Adam
  lr: 0.01
  weight_decay: 0.001

loss:
  name: ConvectionMSEPDELoss
  convection: [1, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30]

  regularization: 1

scheduler:
  end: 15
  start: 0
  step: 1

  data:
    train:
      batch_size: full
      shuffle: False
      sampler:
        name: RandomSampler
        replacement: False
        percent_samples: 0.1
      pde:
        convection: [1, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30]
        l: 6.283185307179586
        n: 100
        snr: 10
        t: 1

    validation:
      batch_size: full
      shuffle: False
      pde:
        convection: [1, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30]
        l: 6.283185307179586
        n: 100
        snr: 0
        t: 1

    test:
      batch_size: full
      shuffle: False
      pde:
        convection: [1, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30]
        l: 6.283185307179586
        n: 100
        snr: 0
        t: 1

training:
  epochs: 10
  stopping:
    patience: 10
